# Generated by Django 3.0.7 on 2020-10-29 15:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_time', models.DateTimeField(auto_now_add=True, db_column='recorded_time')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(db_column='payload', default=None)),
            ],
        ),
    ]
